name: Taller 1

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert ipykernel nbformat
        python -m ipykernel install --user --name=python3
    
    - name: Configuracion tests privados
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.TEST_CLAVE_PRIVADA }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    - name: Descarga de tests privados
      run: |
        git clone git@github.com:Prueba_Test_Privadp/tests.git temp_repo
        mkdir -p tests_descargados
        cp temp_repo/test*.py tests_descargados/
        rm -rf temp_repo

    - name: Ejecución notebook ejercicio1
      run: |
        jupyter nbconvert --to notebook --execute notebooks/ejercicio1.ipynb --output ejercicio1_out.ipynb --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=300 --ExecutePreprocessor.allow_errors=true
    
    - name: Run tests ejercicio1
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)/data pytest tests_descargados/ -v