name: Taller 1

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert ipykernel nbformat
        python -m ipykernel install --user --name=python3

    - name: Configuracion tests
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.clave_privada }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    - name: Descarga de tests
      run: |
        git clone git@github.com:Prueba-Test-Privado/tests.git temp_repo
        mkdir -p tests_descargados/ejercicio1
        cp temp_repo/pruebas/test_*.py tests_descargados 2>/dev/null || echo "Algunos tests no encontrados"
        rm -rf temp_repo

    - name: Ejecución notebook ejercicio1
      run: |
        jupyter nbconvert --to notebook --execute notebooks/ejercicio1.ipynb --output ejercicio1_out.ipynb --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=300 --ExecutePreprocessor.allow_errors=true
    
    - name: Ejecución tests notebook ejercicio1
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)/data pytest tests_descargados/ -v